language: node_js

os:
  - linux
  - osx

node_js: 
  - 8
  - 9
  - 10
  - 12

branches:
  only:
    - master

install:
  - npm i

script:
  - npm run lint
  - npm t
  - npm run build

jobs:
  include:
    - os: linux
      script: npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: always