language: node_js

node_js: 
  - "7"
  - "8"
  - "9"
  - "10"

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: "7"

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lcov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: never
    on_failure: always